### ISSUE TITLE
Question about semver/node dep management

### ISSUE THREAD

**Issue by localnerve** [gruntjs/grunt-contrib-cssmin#213]
I just ran into an issue where clean-css introduced a [bug](https://github.com/jakubpawlowicz/clean-css/issues/553) in 3.2.5 that derailed me for hours.

Is the "proper" node/semver way to guard against this to make clean-css a direct devdep of my project and pin the version more tightly? I know that bugs happen. I'm just wondering the proper way to tighten up.

My apologies if this is an inappropriate forum for this question. Please let me know that too, if it is.

Thanks for reading this.

**Comment by vladikoff** [comment]
@localnerve try `npm shrinkwrap` https://docs.npmjs.com/cli/shrinkwrap
i think npm inc. is working on making shrinkwrap better so it locks everything, it some cases it misses dependencies of dependencies, but hope it works for you!

Also IMHO we do need to lock with `~` instead of a `^` and release new versions for point releases
