### ISSUE TITLE
Docs are nearly useless

### ISSUE THREAD

**Issue by alexandernst** [gruntjs/grunt-contrib-cssmin#224]
Please extend the docs a little bit further as their current state is next to useless.

**Comment by sindresorhus** [comment]
Ironically so is this issue. Please be a bit more specific about what's missing. Keep in mind that this plugin is only a thin wrapper over the `clean-css` module, hence most options are documented over there, as described in the readme.

**Comment by alexandernst** [comment]
All those issues could be avoided with a proper (more extended) docs:

* https://github.com/gruntjs/grunt-contrib-cssmin/issues/222
* https://github.com/gruntjs/grunt-contrib-cssmin/issues/210
* https://github.com/gruntjs/grunt-contrib-cssmin/issues/197 <--- instead of answering "a gazillion times", just write it in the docs
* [#175](https://github.com/gruntjs/grunt-contrib-cssmin/issues/175) , [#162](https://github.com/gruntjs/grunt-contrib-cssmin/issues/162) <--- I saw like 10 of those. How much effort would require to put a note in the docs about `extDot`? 5 minutes? 10 maybe?

Also, examples for some "common"things won't hurt anybody. I see that sourceMap is something that caused quite some opened issues and yet I can't see a single word in the docs (aside from the "this  option enables sourceMap).

Maybe explain why an array with a single object is required for [this](https://github.com/gruntjs/grunt-contrib-cssmin#minify-all-contents-of-a-release-directory-and-add-a-mincss-extension) but not for [this](https://github.com/gruntjs/grunt-contrib-cssmin#combine-two-files-into-one-output-file)? Why not just an object? Or maybe the array lets us do something more? Maybe pass a second object?

**Comment by sindresorhus** [comment]
> #222
#210
#197 <--- instead of answering "a gazillion times", just write it in the docs
#175 , #162 <--- I saw like 10 of those. How much effort would require to put a note in the docs about extDot? 5 minutes? 10 maybe?

These are all about grunt functionality and nothing specific to this plugin. We're not going to duplicate the grunt docs. The problem is that nobody reads the grunt docs before coming here.

> I see that sourceMap is something that caused quite some opened issues and yet I can't see a single word in the docs (aside from the "this option enables sourceMap).

What more do you want it to say? It does exactly what it says and produces a Source Map.

> Maybe explain why an array with a single object is required for this but not for this? Why not just an object? Or maybe the array lets us do something more? Maybe pass a second object?

This is all grunt again. Nothing specific to this plugin.
