### ISSUE TITLE
Add Source Mapping Support

### ISSUE THREAD

**Issue by ScottSmith95** [gruntjs/grunt-contrib-cssmin#58]
If possible, it would be excellent for this plugin to include the option to generate or update existing source maps for CSS files.

**Comment by lancehudson** [comment]
jakubpawlowicz/clean-css#125 is completed, source maps should be able to be enabled in grunt-contrib-cssmin.

**Comment by danny-englander** [comment]
@lancehudson, is there any documentation for this? The method used in https://github.com/gruntjs/grunt-contrib-cssmin/issues/155 doesn't seem to be working.

**Comment by lancehudson** [comment]
Hmm I tried to write a patch and realized i needed usemin to support it as well.

I couldn't find much as far as documentation, I was using the unit tests
https://github.com/jakubpawlowicz/clean-css/blob/master/test/source-map-test.js
 and 
https://github.com/jakubpawlowicz/clean-css#how-to-use-clean-css-programmatically

I was going to pass it the existing source maps as strings, so that it would handle my sass code.

 Later today I will see if I can use it directly.
